### ISSUE TITLE
No code

### ISSUE THREAD

**Issue by PanJohnny** [hugeblank/allium#2]
Only example mod ![IMG-20220220-WA0001-01.jpeg](https://user-images.githubusercontent.com/67548122/156729770-924111bf-085a-419b-9680-1725bae0689d.jpeg)

**Comment by hugeblank** [comment]
for now

**Comment by fatboychummy** [comment]
![20220205_125502](https://user-images.githubusercontent.com/39929480/156797716-b4e2c9d9-1605-4669-bada-6d952228fe15.jpg)
My cat is better than yours @PanJohnny, therefor you have no say here.

**Comment by PanJohnny** [comment]
Cute cat @fatboychummy

**Comment by Benonardo** [comment]
I hope my cat is cute enough
![200px-ScratchCat-Small](https://user-images.githubusercontent.com/75318636/156938902-b4827745-9067-4497-90c5-faac44c18443.png)

**Comment by PanJohnny** [comment]
@Benonardo scratch cat cute ngl

**Comment by PseudoDistant** [comment]
![no code](https://user-images.githubusercontent.com/67613281/156938950-ae419dd5-dcc7-4ffc-928c-aa5737da48d9.png)

**Comment by PanJohnny** [comment]
This issue is officialy designated for cats

**Comment by MrRubberDucky** [comment]
![obraz](https://user-images.githubusercontent.com/79613254/156939570-f2ce6512-911e-4f61-9542-b423f736bec6.png)

**Comment by hugeblank** [comment]
cease.
