### ISSUE TITLE
show 1.18 branch some love

### ISSUE THREAD

**Issue by Merith-TK** [hugeblank/allium#37]
Please? Pretty Please? 

extreme pwetty pweeze?

**Comment by hugeblank** [comment]
Your wish is my command, kinda. 

It's caught up with 1.19, but has a fun little (non-crashing) error that I can't be bothered to fix. Have fun with that! LOL

**Comment by Merith-TK** [comment]
whats that non-crashing bug?

**Comment by hugeblank** [comment]
It's a concurrent modification exception that happens when interacting with a block, I discovered it in testing wetworks, the script where if you right click a concrete powder block with a water bottle it turns into concrete.

**Comment by hugeblank** [comment]
I found the fix to the above issue! I'll look into cherry-picking the commit.
